animal = "     Juan PABlo vera     "
print(animal.upper())
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.find("PAB"))
print(animal.replace("nPAB", "p"))
print("nPAB" in animal)
print("nPAB" not in animal)
